# Generated by Django 4.1.6 on 2023-02-09 22:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Axis', '0041_auto_20210115_1325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='AxisCustomer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
